server:
  port: 9000

spring:
  application:
    name: code-server-${api.config.version}
  profiles:
    active: dev

api:
  config:
    version: v1


mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.auto.codeserver.model.**
